### ISSUE TITLE
compilation issue ` Cannot inject following chunk after stream has ended`

### ISSUE THREAD

**Issue by jaybe78** [brillout/react-streaming#11] opened 2022-06-28 07:42 UTC
Hello,

I'm getting a really odd issue which seems to be related to `React.Suspense`. It happens randomly so it's really not easy to be sure of the real cause of the problem

The below code wraps a `Route` component with `Suspense` within `element` and sometimes triggers a compilation issue

```
<Routes>
          <Route path="/" element={
               <React.Suspense
        fallback={<span className="no-result-search">Loading...</span>}
      >
              <Home />
               </React.Suspense>
                   } />
             <Route path="about" element={<About />} />
        </Routes>
```

Below is the compilation issue.
It happens for `npm run dev` and `prod` build as well

```
Error: [react-streaming][Wrong Usage] Cannot inject following chunk after stream has ended: `<script id="vite-plugin-ssr_pageContext" type="application/json">{"pageContext":{"_pageId":"/pages/all","pageProps":{"translations":{"app_name":"Hello","default":{"app_name":"Hello"}}
...
```

What I've noticed is that, If instead I move the `Suspense` outside `<Routes/>`, the issue seems to go away:

```
<React.Suspense
        fallback={<span className="no-result-search">Loading...</span>}
      >
        <Routes>
          <Route path="/" element={

              <Home />

                   } />
             <Route path="about" element={<About />} />
        </Routes>
      </React.Suspense>
```

Reproducible there but not everytime
 https://github.com/jaybe78/vps-webpack5-redux-streaming-test/tree/react-intl/production-build-fail

**Comment by brillout** [comment] 2022-06-28 08:40
vps version?

**Comment by jaybe78** [comment] 2022-06-28 09:14
0.42

**Comment by brillout** [comment] 2022-06-28 10:43
I couldn't reproduce a single time. Even when changing the "star wars API" response delay.

Any instructions to occasionally reproduce this?

**Comment by brillout** [comment] 2022-06-28 10:44
FYI use `DEBUG=vps:stream npm run dev` to know more.

**Comment by brillout** [comment] 2022-06-28 11:58
I may have found the reason. Stay tuned.

**Comment by brillout** [comment] 2022-06-28 18:27
> I may have found the reason. Stay tuned.

Actually, I double checked and the implementation is correct.

I'll need to be able to reproduce this in order to further dig.

Closing in the meantime, I'll re-open if I can reproduce.

**Closed by brillout** 2022-06-28 18:27 UTC

**Comment by jaybe78** [comment] 2022-06-28 22:28
I was not able to reproduce it... It's very random.

**Comment by brillout** [comment] 2022-06-30 15:35
FYI the plan here is to wait until someone hits this bug and can provide a reliable reproduction.

But let me know if your workaround doesn't work out, I'll then double-check the code again. (But a reproduction would make debugging this a *lot* easier.)
